#!/bin/sh

# show help
# pod2man /usr/bin/mmdebstrap | man -l -

# deps
# sudo apt-get install -y --no-install-recommends mmdebstrap binfmt-support qemu-user-static

# mmdebootstrap default sources
#deb [signed-by="/usr/share/keyrings/debian-archive-keyring.gpg"] http://deb.debian.org/debian bookworm main contrib
#deb [signed-by="/usr/share/keyrings/debian-archive-keyring.gpg"] http://deb.debian.org/debian bookworm-updates main contrib
#deb [signed-by="/usr/share/keyrings/debian-archive-keyring.gpg"] http://security.debian.org/debian-security bookworm-security main contrib

# tsinghua lxc-image sources
# Generated by distrobuilder
#deb http://deb.debian.org/debian bookworm main
#deb http://deb.debian.org/debian bookworm-updates main
#deb http://deb.debian.org/debian-security/ bookworm-security main

# customize
#--aptopt='Apt::Install-Recommends "true"'
#--customize-hook='echo host > "$1/etc/hostname"'
#--customize-hook='echo "127.0.0.1 localhost host" > "$1/etc/hosts"'

# apt cache
# --skip=download/empty --setup-hook='mkdir -p ./cache "$1"/var/cache/apt/archives/' \
# --setup-hook='sync-in ./cache /var/cache/apt/archives/' \
# --customize-hook='sync-out /var/cache/apt/archives ./cache' \

# final define sources
#--customize-hook='echo "\
#deb [signed-by="/usr/share/keyrings/debian-archive-keyring.gpg"] http://deb.debian.org/debian bookworm main contrib
#deb [signed-by="/usr/share/keyrings/debian-archive-keyring.gpg"] http://deb.debian.org/debian bookworm-updates main contrib
#deb [signed-by="/usr/share/keyrings/debian-archive-keyring.gpg"] http://security.debian.org/debian-security bookworm-security main contrib\
#" > $1/etc/apt/sources.list' \

# define sources argument
#"\
#deb [signed-by=\"/usr/share/keyrings/debian-archive-keyring.gpg\"] http://mirrors.ustc.edu.cn/debian bookworm main contrib
#deb [signed-by=\"/usr/share/keyrings/debian-archive-keyring.gpg\"] http://mirrors.ustc.edu.cn/debian bookworm-updates main contrib
#deb [signed-by=\"/usr/share/keyrings/debian-archive-keyring.gpg\"] http://mirrors.ustc.edu.cn/debian-security bookworm-security main contrib\
#" \

# reduce size
	# --dpkgopt='path-exclude=/usr/share/man/*' \
	# --dpkgopt='path-include=/usr/share/man/man[1-9]/*' \
	# --dpkgopt='path-exclude=/usr/share/locale/*' \
	# --dpkgopt='path-include=/usr/share/locale/locale.alias' \
	# --dpkgopt='path-exclude=/usr/share/doc/*' \
	# --dpkgopt='path-include=/usr/share/doc/*/copyright' \
	# --dpkgopt='path-include=/usr/share/doc/*/changelog.Debian.*' \
	# --dpkgopt='path-exclude=/usr/share/{doc,info,man,omf,help,gnome/help}/*' \

# https://github.com/kata-containers/kata-containers/pull/1189/commits/9897238f3a0716a4a30c44b1a554be584ff12ec2
# chroot $ROOTFS_DIR rm -rf /usr/share/{bash-completion,bug,doc,info,lintian,locale,man,menu,misc,pixmaps,terminfo,zoneinfo,zsh}


#/etc/resolv.conf
#/etc/hosts
#/etc/apt/sources.list


arch=arm64
dist_version=bookworm
#mirrors='http://mirrors.ustc.edu.cn/debian/'
mirrors="http://mirrors.ustc.edu.cn/debian/"
output="debian-${dist_version}-${arch}-rootfs.tar"

sudo mmdebstrap \
	--setup-hook='cat $1/etc/apt/sources.list' \
	--architectures="${arch}" \
	--variant=minbase \
	--components="main,contrib" \
	--include="ca-certificates,xz-utils" \
	--skip=download/empty \
	--setup-hook='mkdir -p ./cache "$1"/var/cache/apt/archives/' \
	--setup-hook='sync-in ./cache /var/cache/apt/archives/' \
	--customize-hook='sync-out /var/cache/apt/archives ./cache' \
	--customize-hook='echo "\
nameserver 8.8.8.8
nameserver 8.8.4.4\
" > $1/etc/resolv.conf' \
	--customize-hook='echo "\
# IPv4.
127.0.0.1   localhost.localdomain localhost

# IPv6.
::1         localhost.localdomain localhost ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
ff02::3     ip6-allhosts\
" > $1/etc/hosts' \
	"${dist_version}" \
	- |
	tar --delete --wildcards "./dev/*" | gzip >"${output}.gz"

echo "${output}.gz" is ready
gzip -dkc "${output}.gz" | xz -T0 >"${output}.xz"
echo "${output}.xz" is ready
